#Configuracion del puerto

server.port = 8090

#Spring data JPA conexion con

spring.datasource.url=jdbc:postgresql://localhost:5432/platzi_play_db
spring.datasource.username=leonardo
spring.datasource.password=leonardo.platzi


#Langchain4j Implememtacion de IA

langchain4j.open-ai.chat-model.api-key= demo
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG

