spring.profiles.active=dev


#Configuracion del contexto y nombre de la aplicacion

spring.application.name=play
server.servlet.context-path=/platzi-play/api

#Postgre

spring.datasource.driver-class-name=org.postgresql.Driver

#Langchain4j Implememtacion de IA

langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
